# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1082, 678)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logos/N.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.optionsGrid = QtWidgets.QGridLayout(self.tab)
        self.optionsGrid.setContentsMargins(0, 0, 0, 0)
        self.optionsGrid.setObjectName("optionsGrid")
        self.tabWidget.addTab(self.tab, "")
        self.roi = QtWidgets.QWidget()
        self.roi.setObjectName("roi")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.roi)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.xrdWidget = XrdWidget(self.roi)
        self.xrdWidget.setObjectName("xrdWidget")
        self.horizontalLayout.addWidget(self.xrdWidget)
        self.tabWidget.addTab(self.roi, "")
        self.com = QtWidgets.QWidget()
        self.com.setObjectName("com")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.com)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comWidget = ComWidget(self.com)
        self.comWidget.setObjectName("comWidget")
        self.horizontalLayout_2.addWidget(self.comWidget)
        self.tabWidget.addTab(self.com, "")
        self.xrf = QtWidgets.QWidget()
        self.xrf.setObjectName("xrf")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.xrf)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.xrfWidget = XrfWidget(self.xrf)
        self.xrfWidget.setObjectName("xrfWidget")
        self.horizontalLayout_3.addWidget(self.xrfWidget)
        self.tabWidget.addTab(self.xrf, "")
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.scanClassBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scanClassBox.sizePolicy().hasHeightForWidth())
        self.scanClassBox.setSizePolicy(sizePolicy)
        self.scanClassBox.setMinimumSize(QtCore.QSize(100, 0))
        self.scanClassBox.setBaseSize(QtCore.QSize(200, 0))
        self.scanClassBox.setMaxVisibleItems(100)
        self.scanClassBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.scanClassBox.setObjectName("scanClassBox")
        self.gridLayout.addWidget(self.scanClassBox, 0, 1, 1, 1)
        self.logoLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logoLabel.sizePolicy().hasHeightForWidth())
        self.logoLabel.setSizePolicy(sizePolicy)
        self.logoLabel.setMinimumSize(QtCore.QSize(260, 0))
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap(":/logos/nanomax.png"))
        self.logoLabel.setObjectName("logoLabel")
        self.gridLayout.addWidget(self.logoLabel, 0, 0, 3, 1)
        self.loadButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadButton.sizePolicy().hasHeightForWidth())
        self.loadButton.setSizePolicy(sizePolicy)
        self.loadButton.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.loadButton.setAutoDefault(True)
        self.loadButton.setDefault(True)
        self.loadButton.setObjectName("loadButton")
        self.gridLayout.addWidget(self.loadButton, 1, 4, 1, 1)
        self.filenameBox = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filenameBox.sizePolicy().hasHeightForWidth())
        self.filenameBox.setSizePolicy(sizePolicy)
        self.filenameBox.setMinimumSize(QtCore.QSize(100, 0))
        self.filenameBox.setBaseSize(QtCore.QSize(200, 0))
        self.filenameBox.setPlaceholderText("")
        self.filenameBox.setObjectName("filenameBox")
        self.gridLayout.addWidget(self.filenameBox, 1, 1, 1, 1)
        self.browseButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseButton.sizePolicy().hasHeightForWidth())
        self.browseButton.setSizePolicy(sizePolicy)
        self.browseButton.setMaximumSize(QtCore.QSize(1000000, 16777215))
        self.browseButton.setObjectName("browseButton")
        self.gridLayout.addWidget(self.browseButton, 1, 3, 1, 1)
        self.appendBox = QtWidgets.QCheckBox(self.centralwidget)
        self.appendBox.setObjectName("appendBox")
        self.gridLayout.addWidget(self.appendBox, 1, 2, 1, 1)
        self.scanNumberBox = QtWidgets.QSpinBox(self.centralwidget)
        self.scanNumberBox.setMaximum(999999)
        self.scanNumberBox.setObjectName("scanNumberBox")
        self.gridLayout.addWidget(self.scanNumberBox, 0, 2, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1082, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.scanClassBox, self.scanNumberBox)
        MainWindow.setTabOrder(self.scanNumberBox, self.filenameBox)
        MainWindow.setTabOrder(self.filenameBox, self.browseButton)
        MainWindow.setTabOrder(self.browseButton, self.loadButton)
        MainWindow.setTabOrder(self.loadButton, self.tabWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NanoMAX Scan Viewer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Scan options"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.roi), _translate("MainWindow", "XRD region of interest"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.com), _translate("MainWindow", "XRD center of mass"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.xrf), _translate("MainWindow", "XRF region of interest"))
        self.scanClassBox.setToolTip(_translate("MainWindow", "<html><head/><body><p>Available Scan subclasses</p></body></html>"))
        self.loadButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Go!</p></body></html>"))
        self.loadButton.setText(_translate("MainWindow", "Load"))
        self.filenameBox.setText(_translate("MainWindow", "<input file>"))
        self.browseButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Browse for data files</p></body></html>"))
        self.browseButton.setText(_translate("MainWindow", "Browse..."))
        self.appendBox.setText(_translate("MainWindow", "Append"))

from widgets.ComWidget import ComWidget
from widgets.XrdWidget import XrdWidget
from widgets.XrfWidget import XrfWidget
import design_rc
