# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from silx.gui import qt as QtCore
QtGui = QtCore
QtWidgets = QtCore

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1082, 678)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logos/N.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.optionsGrid = QtWidgets.QGridLayout(self.tab)
        self.optionsGrid.setObjectName("optionsGrid")
        self.tabWidget.addTab(self.tab, "")
        self.tab2d = QtWidgets.QWidget()
        self.tab2d.setObjectName("tab2d")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab2d)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.tab2d)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.dataSource2dBox = QtWidgets.QComboBox(self.tab2d)
        self.dataSource2dBox.setMinimumSize(QtCore.QSize(100, 0))
        self.dataSource2dBox.setObjectName("dataSource2dBox")
        self.gridLayout_4.addWidget(self.dataSource2dBox, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 2, 1, 1)
        self.xrdWidget = XrdWidget(self.tab2d)
        self.xrdWidget.setObjectName("xrdWidget")
        self.gridLayout_4.addWidget(self.xrdWidget, 2, 0, 1, 3)
        self.tabWidget.addTab(self.tab2d, "")
        self.tab2dCom = QtWidgets.QWidget()
        self.tab2dCom.setObjectName("tab2dCom")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab2dCom)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.comDirBox = QtWidgets.QComboBox(self.tab2dCom)
        self.comDirBox.setMinimumSize(QtCore.QSize(100, 0))
        self.comDirBox.setObjectName("comDirBox")
        self.gridLayout_3.addWidget(self.comDirBox, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab2dCom)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 2, 1, 1)
        self.comWidget = ComWidget(self.tab2dCom)
        self.comWidget.setObjectName("comWidget")
        self.gridLayout_3.addWidget(self.comWidget, 1, 0, 1, 3)
        self.tabWidget.addTab(self.tab2dCom, "")
        self.tab1d = QtWidgets.QWidget()
        self.tab1d.setObjectName("tab1d")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab1d)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.dataSource1dBox = QtWidgets.QComboBox(self.tab1d)
        self.dataSource1dBox.setMinimumSize(QtCore.QSize(100, 0))
        self.dataSource1dBox.setObjectName("dataSource1dBox")
        self.gridLayout_5.addWidget(self.dataSource1dBox, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab1d)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 2, 1, 1)
        self.xrfWidget = XrfWidget(self.tab1d)
        self.xrfWidget.setObjectName("xrfWidget")
        self.gridLayout_5.addWidget(self.xrfWidget, 1, 0, 1, 3)
        self.tabWidget.addTab(self.tab1d, "")
        self.tab0d = QtWidgets.QWidget()
        self.tab0d.setObjectName("tab0d")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab0d)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.dataSource0dBox = QtWidgets.QComboBox(self.tab0d)
        self.dataSource0dBox.setMinimumSize(QtCore.QSize(100, 0))
        self.dataSource0dBox.setObjectName("dataSource0dBox")
        self.gridLayout_6.addWidget(self.dataSource0dBox, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab0d)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 0, 2, 1, 1)
        self.scalarWidget = ScalarWidget(self.tab0d)
        self.scalarWidget.setObjectName("scalarWidget")
        self.gridLayout_6.addWidget(self.scalarWidget, 1, 0, 1, 3)
        self.tabWidget.addTab(self.tab0d, "")
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.scanClassBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scanClassBox.sizePolicy().hasHeightForWidth())
        self.scanClassBox.setSizePolicy(sizePolicy)
        self.scanClassBox.setMinimumSize(QtCore.QSize(100, 0))
        self.scanClassBox.setBaseSize(QtCore.QSize(200, 0))
        self.scanClassBox.setMaxVisibleItems(100)
        self.scanClassBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.scanClassBox.setObjectName("scanClassBox")
        self.gridLayout.addWidget(self.scanClassBox, 0, 1, 1, 1)
        self.logoLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logoLabel.sizePolicy().hasHeightForWidth())
        self.logoLabel.setSizePolicy(sizePolicy)
        self.logoLabel.setMinimumSize(QtCore.QSize(260, 0))
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap(":/logos/nanomax.png"))
        self.logoLabel.setObjectName("logoLabel")
        self.gridLayout.addWidget(self.logoLabel, 0, 0, 3, 1)
        self.loadButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadButton.sizePolicy().hasHeightForWidth())
        self.loadButton.setSizePolicy(sizePolicy)
        self.loadButton.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.loadButton.setAutoDefault(True)
        self.loadButton.setDefault(True)
        self.loadButton.setObjectName("loadButton")
        self.gridLayout.addWidget(self.loadButton, 1, 4, 1, 1)
        self.filenameBox = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filenameBox.sizePolicy().hasHeightForWidth())
        self.filenameBox.setSizePolicy(sizePolicy)
        self.filenameBox.setMinimumSize(QtCore.QSize(100, 0))
        self.filenameBox.setBaseSize(QtCore.QSize(200, 0))
        self.filenameBox.setPlaceholderText("")
        self.filenameBox.setObjectName("filenameBox")
        self.gridLayout.addWidget(self.filenameBox, 1, 1, 1, 1)
        self.browseButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseButton.sizePolicy().hasHeightForWidth())
        self.browseButton.setSizePolicy(sizePolicy)
        self.browseButton.setMaximumSize(QtCore.QSize(1000000, 16777215))
        self.browseButton.setObjectName("browseButton")
        self.gridLayout.addWidget(self.browseButton, 1, 3, 1, 1)
        self.appendBox = QtWidgets.QCheckBox(self.centralwidget)
        self.appendBox.setObjectName("appendBox")
        self.gridLayout.addWidget(self.appendBox, 1, 2, 1, 1)
        self.scanNumberBox = QtWidgets.QSpinBox(self.centralwidget)
        self.scanNumberBox.setMaximum(999999)
        self.scanNumberBox.setObjectName("scanNumberBox")
        self.gridLayout.addWidget(self.scanNumberBox, 0, 2, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1082, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.scanClassBox, self.scanNumberBox)
        MainWindow.setTabOrder(self.scanNumberBox, self.filenameBox)
        MainWindow.setTabOrder(self.filenameBox, self.browseButton)
        MainWindow.setTabOrder(self.browseButton, self.loadButton)
        MainWindow.setTabOrder(self.loadButton, self.tabWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NanoMAX Scan Viewer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Scan options"))
        self.label.setText(_translate("MainWindow", "data source"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2d), _translate("MainWindow", "Image data"))
        self.label_2.setText(_translate("MainWindow", "COM direction"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2dCom), _translate("MainWindow", "Image center of mass"))
        self.label_3.setText(_translate("MainWindow", "data source"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1d), _translate("MainWindow", "Spectral data"))
        self.label_4.setText(_translate("MainWindow", "data source"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab0d), _translate("MainWindow", "Scalar data"))
        self.scanClassBox.setToolTip(_translate("MainWindow", "<html><head/><body><p>Available Scan subclasses</p></body></html>"))
        self.loadButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Go!</p></body></html>"))
        self.loadButton.setText(_translate("MainWindow", "Load"))
        self.filenameBox.setText(_translate("MainWindow", "<input file>"))
        self.browseButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Browse for data files</p></body></html>"))
        self.browseButton.setText(_translate("MainWindow", "Browse..."))
        self.appendBox.setText(_translate("MainWindow", "Append"))

from widgets.ComWidget import ComWidget
from widgets.ScalarWidget import ScalarWidget
from widgets.XrdWidget import XrdWidget
from widgets.XrfWidget import XrfWidget
import design_rc
