{% set version = "0.4.3" %}

package:
  name: nanomax-analysis-utils
  version: {{ version }}

source:
  path: ../

build:
  number: 1
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt
requirements:
  host:
    - python
  run:
    - numpy
    - h5py
    - silx
